# Generated by Django 2.0.1 on 2018-07-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
