# Generated by Django 2.0.6 on 2018-07-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='store_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=200)),
                ('item_price', models.IntegerField()),
                ('item_is_available', models.BooleanField(default=True)),
                ('item_description', models.CharField(max_length=500)),
            ],
        ),
    ]
