# Generated by Django 2.0.7 on 2018-07-10 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='storeItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(default='NoName', max_length=200)),
                ('item_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item_is_available', models.BooleanField(default=True)),
                ('item_description', models.CharField(default='None', max_length=500)),
                ('item_image', models.FileField(default='placeholder', upload_to='')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
