# Generated by Django 2.0.7 on 2018-07-10 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='item_image',
            field=models.FileField(default='placeholder', upload_to=''),
        ),
    ]
